FROM dxflrs/garage:v2.1.0 as garage-binary

FROM debian:12-slim

RUN apt-get update && apt-get install -y curl bash jq && rm -rf /var/lib/apt/lists/*

COPY --from=garage-binary /garage /garage

COPY init.sh /init.sh
RUN chmod +x /init.sh

ENTRYPOINT ["/init.sh"]
