// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: documents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const confirmDocumentUpload = `-- name: ConfirmDocumentUpload :one
UPDATE vehicle_documents
SET upload_url = NULL
WHERE id = $1
RETURNING id, vehicle_id, object_key, filename, upload_url, created_at
`

func (q *Queries) ConfirmDocumentUpload(ctx context.Context, id uuid.UUID) (VehicleDocument, error) {
	row := q.db.QueryRow(ctx, confirmDocumentUpload, id)
	var i VehicleDocument
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.Filename,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const countDocumentsByVehicle = `-- name: CountDocumentsByVehicle :one
SELECT COUNT(*) FROM vehicle_documents
WHERE vehicle_id = $1
`

func (q *Queries) CountDocumentsByVehicle(ctx context.Context, vehicleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsByVehicle, vehicleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocument = `-- name: CreateDocument :one
INSERT INTO vehicle_documents (
    vehicle_id, object_key, filename, upload_url
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, vehicle_id, object_key, filename, upload_url, created_at
`

type CreateDocumentParams struct {
	VehicleID uuid.UUID
	ObjectKey string
	Filename  string
	UploadUrl *string
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (VehicleDocument, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.VehicleID,
		arg.ObjectKey,
		arg.Filename,
		arg.UploadUrl,
	)
	var i VehicleDocument
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.Filename,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteDocument = `-- name: DeleteDocument :exec
DELETE FROM vehicle_documents
WHERE id = $1
`

func (q *Queries) DeleteDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDocument, id)
	return err
}

const getDocument = `-- name: GetDocument :one
SELECT id, vehicle_id, object_key, filename, upload_url, created_at FROM vehicle_documents
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetDocument(ctx context.Context, id uuid.UUID) (VehicleDocument, error) {
	row := q.db.QueryRow(ctx, getDocument, id)
	var i VehicleDocument
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.Filename,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getDocumentByKey = `-- name: GetDocumentByKey :one
SELECT id, vehicle_id, object_key, filename, upload_url, created_at FROM vehicle_documents
WHERE vehicle_id = $1 AND object_key = $2 LIMIT 1
`

type GetDocumentByKeyParams struct {
	VehicleID uuid.UUID
	ObjectKey string
}

func (q *Queries) GetDocumentByKey(ctx context.Context, arg GetDocumentByKeyParams) (VehicleDocument, error) {
	row := q.db.QueryRow(ctx, getDocumentByKey, arg.VehicleID, arg.ObjectKey)
	var i VehicleDocument
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.Filename,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listDocumentsByVehicle = `-- name: ListDocumentsByVehicle :many
SELECT id, vehicle_id, object_key, filename, upload_url, created_at FROM vehicle_documents
WHERE vehicle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListDocumentsByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]VehicleDocument, error) {
	rows, err := q.db.Query(ctx, listDocumentsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleDocument{}
	for rows.Next() {
		var i VehicleDocument
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.ObjectKey,
			&i.Filename,
			&i.UploadUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
