// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entities.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countEntities = `-- name: CountEntities :one
SELECT COUNT(*) FROM entities
`

func (q *Queries) CountEntities(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEntities)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEntitiesByType = `-- name: CountEntitiesByType :one
SELECT COUNT(*) FROM entities
WHERE entity_type = $1
`

func (q *Queries) CountEntitiesByType(ctx context.Context, entityType string) (int64, error) {
	row := q.db.QueryRow(ctx, countEntitiesByType, entityType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (
    name, entity_type, description, contact_email, website, address, certified_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, name, entity_type, description, contact_email, website, address, certified_by, created_at, updated_at
`

type CreateEntityParams struct {
	Name         string
	EntityType   string
	Description  string
	ContactEmail string
	Website      string
	Address      []byte
	CertifiedBy  *uuid.UUID
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, createEntity,
		arg.Name,
		arg.EntityType,
		arg.Description,
		arg.ContactEmail,
		arg.Website,
		arg.Address,
		arg.CertifiedBy,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EntityType,
		&i.Description,
		&i.ContactEmail,
		&i.Website,
		&i.Address,
		&i.CertifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM entities
WHERE id = $1
`

func (q *Queries) DeleteEntity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEntity, id)
	return err
}

const getEntity = `-- name: GetEntity :one
SELECT id, name, entity_type, description, contact_email, website, address, certified_by, created_at, updated_at FROM entities
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntity(ctx context.Context, id uuid.UUID) (Entity, error) {
	row := q.db.QueryRow(ctx, getEntity, id)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EntityType,
		&i.Description,
		&i.ContactEmail,
		&i.Website,
		&i.Address,
		&i.CertifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntities = `-- name: ListEntities :many
SELECT id, name, entity_type, description, contact_email, website, address, certified_by, created_at, updated_at FROM entities
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListEntitiesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEntities(ctx context.Context, arg ListEntitiesParams) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntities, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EntityType,
			&i.Description,
			&i.ContactEmail,
			&i.Website,
			&i.Address,
			&i.CertifiedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByType = `-- name: ListEntitiesByType :many
SELECT id, name, entity_type, description, contact_email, website, address, certified_by, created_at, updated_at FROM entities
WHERE entity_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListEntitiesByTypeParams struct {
	EntityType string
	Limit      int32
	Offset     int32
}

func (q *Queries) ListEntitiesByType(ctx context.Context, arg ListEntitiesByTypeParams) ([]Entity, error) {
	rows, err := q.db.Query(ctx, listEntitiesByType, arg.EntityType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entity{}
	for rows.Next() {
		var i Entity
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.EntityType,
			&i.Description,
			&i.ContactEmail,
			&i.Website,
			&i.Address,
			&i.CertifiedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntity = `-- name: UpdateEntity :one
UPDATE entities
SET name = $2, description = $3, contact_email = $4, website = $5, address = $6, updated_at = NOW()
WHERE id = $1
RETURNING id, name, entity_type, description, contact_email, website, address, certified_by, created_at, updated_at
`

type UpdateEntityParams struct {
	ID           uuid.UUID
	Name         string
	Description  string
	ContactEmail string
	Website      string
	Address      []byte
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error) {
	row := q.db.QueryRow(ctx, updateEntity,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.ContactEmail,
		arg.Website,
		arg.Address,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.EntityType,
		&i.Description,
		&i.ContactEmail,
		&i.Website,
		&i.Address,
		&i.CertifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
