// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    vehicle_id,
    entity_id,
    event_type,
    title,
    description,
    event_date,
    location,
    metadata
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
RETURNING id, vehicle_id, entity_id, event_type, title, description, event_date, location, metadata, cid, cid_source_json, cid_source_cbor_b64, blockchain_tx_id, created_at
`

type CreateEventParams struct {
	VehicleID   uuid.UUID
	EntityID    *uuid.UUID
	EventType   string
	Title       string
	Description string
	EventDate   time.Time
	Location    string
	Metadata    []byte
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.VehicleID,
		arg.EntityID,
		arg.EventType,
		arg.Title,
		arg.Description,
		arg.EventDate,
		arg.Location,
		arg.Metadata,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.EntityID,
		&i.EventType,
		&i.Title,
		&i.Description,
		&i.EventDate,
		&i.Location,
		&i.Metadata,
		&i.Cid,
		&i.CidSourceJson,
		&i.CidSourceCborB64,
		&i.BlockchainTxID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEvent = `-- name: DeleteEvent :exec
DELETE FROM events
WHERE id = $1
`

func (q *Queries) DeleteEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEvent, id)
	return err
}

const getEvent = `-- name: GetEvent :one
SELECT id, vehicle_id, entity_id, event_type, title, description, event_date, location, metadata, cid, cid_source_json, cid_source_cbor_b64, blockchain_tx_id, created_at FROM events
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEvent(ctx context.Context, id uuid.UUID) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.EntityID,
		&i.EventType,
		&i.Title,
		&i.Description,
		&i.EventDate,
		&i.Location,
		&i.Metadata,
		&i.Cid,
		&i.CidSourceJson,
		&i.CidSourceCborB64,
		&i.BlockchainTxID,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsByEntity = `-- name: ListEventsByEntity :many
SELECT id, vehicle_id, entity_id, event_type, title, description, event_date, location, metadata, cid, cid_source_json, cid_source_cbor_b64, blockchain_tx_id, created_at FROM events
WHERE entity_id = $1
ORDER BY event_date DESC
`

func (q *Queries) ListEventsByEntity(ctx context.Context, entityID *uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.EntityID,
			&i.EventType,
			&i.Title,
			&i.Description,
			&i.EventDate,
			&i.Location,
			&i.Metadata,
			&i.Cid,
			&i.CidSourceJson,
			&i.CidSourceCborB64,
			&i.BlockchainTxID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByVehicle = `-- name: ListEventsByVehicle :many
SELECT id, vehicle_id, entity_id, event_type, title, description, event_date, location, metadata, cid, cid_source_json, cid_source_cbor_b64, blockchain_tx_id, created_at FROM events
WHERE vehicle_id = $1
ORDER BY event_date DESC
`

func (q *Queries) ListEventsByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.EntityID,
			&i.EventType,
			&i.Title,
			&i.Description,
			&i.EventDate,
			&i.Location,
			&i.Metadata,
			&i.Cid,
			&i.CidSourceJson,
			&i.CidSourceCborB64,
			&i.BlockchainTxID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByVehicleWithEntity = `-- name: ListEventsByVehicleWithEntity :many
SELECT
    e.id, e.vehicle_id, e.entity_id, e.event_type, e.title, e.description, e.event_date, e.location, e.metadata, e.cid, e.cid_source_json, e.cid_source_cbor_b64, e.blockchain_tx_id, e.created_at,
    ent.name AS entity_name,
    ent.logo_object_key AS entity_logo_object_key
FROM events e
LEFT JOIN entities ent ON e.entity_id = ent.id
WHERE e.vehicle_id = $1
ORDER BY e.event_date DESC
`

type ListEventsByVehicleWithEntityRow struct {
	ID                  uuid.UUID
	VehicleID           uuid.UUID
	EntityID            *uuid.UUID
	EventType           string
	Title               string
	Description         string
	EventDate           time.Time
	Location            string
	Metadata            []byte
	Cid                 *string
	CidSourceJson       *string
	CidSourceCborB64    *string
	BlockchainTxID      string
	CreatedAt           time.Time
	EntityName          *string
	EntityLogoObjectKey *string
}

func (q *Queries) ListEventsByVehicleWithEntity(ctx context.Context, vehicleID uuid.UUID) ([]ListEventsByVehicleWithEntityRow, error) {
	rows, err := q.db.Query(ctx, listEventsByVehicleWithEntity, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsByVehicleWithEntityRow{}
	for rows.Next() {
		var i ListEventsByVehicleWithEntityRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.EntityID,
			&i.EventType,
			&i.Title,
			&i.Description,
			&i.EventDate,
			&i.Location,
			&i.Metadata,
			&i.Cid,
			&i.CidSourceJson,
			&i.CidSourceCborB64,
			&i.BlockchainTxID,
			&i.CreatedAt,
			&i.EntityName,
			&i.EntityLogoObjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsForVerification = `-- name: ListEventsForVerification :many
SELECT
    e.id, e.event_type, e.title, e.event_date,
    e.blockchain_tx_id, e.cid,
    ent.name AS entity_name
FROM events e
LEFT JOIN entities ent ON e.entity_id = ent.id
WHERE e.vehicle_id = $1
ORDER BY e.event_date DESC
`

type ListEventsForVerificationRow struct {
	ID             uuid.UUID
	EventType      string
	Title          string
	EventDate      time.Time
	BlockchainTxID string
	Cid            *string
	EntityName     *string
}

func (q *Queries) ListEventsForVerification(ctx context.Context, vehicleID uuid.UUID) ([]ListEventsForVerificationRow, error) {
	rows, err := q.db.Query(ctx, listEventsForVerification, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEventsForVerificationRow{}
	for rows.Next() {
		var i ListEventsForVerificationRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Title,
			&i.EventDate,
			&i.BlockchainTxID,
			&i.Cid,
			&i.EntityName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $2,
    description = $3,
    event_date = $4,
    location = $5,
    metadata = $6,
    cid = $7,
    cid_source_json = $8,
    cid_source_cbor_b64 = $9,
    blockchain_tx_id = $10
WHERE id = $1
RETURNING id, vehicle_id, entity_id, event_type, title, description, event_date, location, metadata, cid, cid_source_json, cid_source_cbor_b64, blockchain_tx_id, created_at
`

type UpdateEventParams struct {
	ID               uuid.UUID
	Title            string
	Description      string
	EventDate        time.Time
	Location         string
	Metadata         []byte
	Cid              *string
	CidSourceJson    *string
	CidSourceCborB64 *string
	BlockchainTxID   string
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.EventDate,
		arg.Location,
		arg.Metadata,
		arg.Cid,
		arg.CidSourceJson,
		arg.CidSourceCborB64,
		arg.BlockchainTxID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.EntityID,
		&i.EventType,
		&i.Title,
		&i.Description,
		&i.EventDate,
		&i.Location,
		&i.Metadata,
		&i.Cid,
		&i.CidSourceJson,
		&i.CidSourceCborB64,
		&i.BlockchainTxID,
		&i.CreatedAt,
	)
	return i, err
}
