// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_images.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachEventImagesToEvent = `-- name: AttachEventImagesToEvent :exec
UPDATE event_images
SET event_id = $2
WHERE upload_session_id = $1
`

type AttachEventImagesToEventParams struct {
	UploadSessionID uuid.UUID
	EventID         *uuid.UUID
}

func (q *Queries) AttachEventImagesToEvent(ctx context.Context, arg AttachEventImagesToEventParams) error {
	_, err := q.db.Exec(ctx, attachEventImagesToEvent, arg.UploadSessionID, arg.EventID)
	return err
}

const confirmEventImageUpload = `-- name: ConfirmEventImageUpload :one
UPDATE event_images
SET cid = $2, upload_url = NULL
WHERE id = $1
RETURNING id, event_id, upload_session_id, object_key, cid, upload_url, created_at
`

type ConfirmEventImageUploadParams struct {
	ID  uuid.UUID
	Cid *string
}

func (q *Queries) ConfirmEventImageUpload(ctx context.Context, arg ConfirmEventImageUploadParams) (EventImage, error) {
	row := q.db.QueryRow(ctx, confirmEventImageUpload, arg.ID, arg.Cid)
	var i EventImage
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UploadSessionID,
		&i.ObjectKey,
		&i.Cid,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const countEventImagesBySession = `-- name: CountEventImagesBySession :one
SELECT COUNT(*) FROM event_images
WHERE upload_session_id = $1
`

func (q *Queries) CountEventImagesBySession(ctx context.Context, uploadSessionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countEventImagesBySession, uploadSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEventImage = `-- name: CreateEventImage :one
INSERT INTO event_images (
    upload_session_id, object_key, upload_url
) VALUES (
    $1, $2, $3
)
RETURNING id, event_id, upload_session_id, object_key, cid, upload_url, created_at
`

type CreateEventImageParams struct {
	UploadSessionID uuid.UUID
	ObjectKey       string
	UploadUrl       *string
}

func (q *Queries) CreateEventImage(ctx context.Context, arg CreateEventImageParams) (EventImage, error) {
	row := q.db.QueryRow(ctx, createEventImage, arg.UploadSessionID, arg.ObjectKey, arg.UploadUrl)
	var i EventImage
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UploadSessionID,
		&i.ObjectKey,
		&i.Cid,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEventImage = `-- name: DeleteEventImage :exec
DELETE FROM event_images
WHERE id = $1
`

func (q *Queries) DeleteEventImage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteEventImage, id)
	return err
}

const deleteOrphanedEventImages = `-- name: DeleteOrphanedEventImages :exec
DELETE FROM event_images
WHERE event_id IS NULL AND created_at < $1
`

func (q *Queries) DeleteOrphanedEventImages(ctx context.Context, createdAt pgtype.Timestamp) error {
	_, err := q.db.Exec(ctx, deleteOrphanedEventImages, createdAt)
	return err
}

const getEventImage = `-- name: GetEventImage :one
SELECT id, event_id, upload_session_id, object_key, cid, upload_url, created_at FROM event_images
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEventImage(ctx context.Context, id uuid.UUID) (EventImage, error) {
	row := q.db.QueryRow(ctx, getEventImage, id)
	var i EventImage
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UploadSessionID,
		&i.ObjectKey,
		&i.Cid,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listEventImagesByEvent = `-- name: ListEventImagesByEvent :many
SELECT id, event_id, upload_session_id, object_key, cid, upload_url, created_at FROM event_images
WHERE event_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEventImagesByEvent(ctx context.Context, eventID *uuid.UUID) ([]EventImage, error) {
	rows, err := q.db.Query(ctx, listEventImagesByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventImage{}
	for rows.Next() {
		var i EventImage
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UploadSessionID,
			&i.ObjectKey,
			&i.Cid,
			&i.UploadUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventImagesBySession = `-- name: ListEventImagesBySession :many
SELECT id, event_id, upload_session_id, object_key, cid, upload_url, created_at FROM event_images
WHERE upload_session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEventImagesBySession(ctx context.Context, uploadSessionID uuid.UUID) ([]EventImage, error) {
	rows, err := q.db.Query(ctx, listEventImagesBySession, uploadSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventImage{}
	for rows.Next() {
		var i EventImage
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UploadSessionID,
			&i.ObjectKey,
			&i.Cid,
			&i.UploadUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanedEventImages = `-- name: ListOrphanedEventImages :many
SELECT id, event_id, upload_session_id, object_key, cid, upload_url, created_at FROM event_images
WHERE event_id IS NULL AND created_at < $1
ORDER BY created_at ASC
`

func (q *Queries) ListOrphanedEventImages(ctx context.Context, createdAt pgtype.Timestamp) ([]EventImage, error) {
	rows, err := q.db.Query(ctx, listOrphanedEventImages, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EventImage{}
	for rows.Next() {
		var i EventImage
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.UploadSessionID,
			&i.ObjectKey,
			&i.Cid,
			&i.UploadUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
