// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Entity struct {
	ID           uuid.UUID
	Name         string
	EntityType   string
	Description  string
	ContactEmail string
	Website      string
	Address      []byte
	CertifiedBy  *uuid.UUID
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type Event struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	EntityID         *uuid.UUID
	EventType        string
	Title            string
	Description      string
	EventDate        time.Time
	Location         string
	Metadata         []byte
	Cid              *string
	CidSourceJson    *string
	CidSourceCborB64 *string
	BlockchainTxID   string
	CreatedAt        time.Time
}

type User struct {
	ID        uuid.UUID
	IsAdmin   bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type UserEntity struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
	Role     string
	AddedAt  time.Time
}

type UserInvitation struct {
	ID             uuid.UUID
	Email          string
	Name           *string
	Token          string
	TokenExpiresAt pgtype.Timestamp
	EntityID       *uuid.UUID
	InvitationType string
	EntityRole     *string
	InvitedAt      pgtype.Timestamp
	ClaimedAt      pgtype.Timestamp
}

type Vehicle struct {
	ID                 uuid.UUID
	OwnerID            *uuid.UUID
	ChassisNumber      string
	LicensePlate       string
	EngineNumber       string
	TransmissionNumber string
	Make               string
	Model              string
	Year               int32
	Color              string
	BodyType           string
	DriveType          string
	GearType           string
	SuspensionType     string
	Cid                *string
	CidSourceJson      *string
	CidSourceCborB64   *string
	BlockchainAssetID  string
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type VehicleDocument struct {
	ID        uuid.UUID
	VehicleID uuid.UUID
	ObjectKey string
	Filename  string
	UploadUrl *string
	CreatedAt pgtype.Timestamptz
}

type VehicleInvitation struct {
	ID             uuid.UUID
	VehicleID      uuid.UUID
	Email          string
	InvitedAt      pgtype.Timestamp
	ClaimedAt      pgtype.Timestamp
	Token          *string
	TokenExpiresAt pgtype.Timestamp
}

type VehiclePhoto struct {
	ID        uuid.UUID
	VehicleID uuid.UUID
	ObjectKey string
	UploadUrl *string
	CreatedAt pgtype.Timestamptz
}

type VehicleShareLink struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	Token            string
	CanViewDetails   bool
	CanViewPhotos    bool
	CanViewDocuments bool
	CanViewHistory   bool
	RecipientEmail   *string
	ExpiresAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
	AccessedCount    int32
	LastAccessedAt   pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}
