// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Entity struct {
	ID            uuid.UUID
	Name          string
	EntityType    string
	Description   string
	ContactEmail  string
	Website       string
	Address       []byte
	CertifiedBy   *uuid.UUID
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	LogoObjectKey *string
}

type Event struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	EntityID         *uuid.UUID
	EventType        string
	Title            string
	Description      string
	EventDate        time.Time
	Location         string
	Metadata         []byte
	Cid              *string
	CidSourceJson    *string
	CidSourceCborB64 *string
	BlockchainTxID   string
	CreatedAt        pgtype.Timestamp
	BlockchainStatus string
}

type EventImage struct {
	ID              uuid.UUID
	EventID         *uuid.UUID
	UploadSessionID uuid.UUID
	ObjectKey       string
	Cid             *string
	UploadUrl       *string
	CreatedAt       pgtype.Timestamp
}

type User struct {
	ID        uuid.UUID
	IsAdmin   bool
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserEntity struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
	Role     string
	AddedAt  pgtype.Timestamp
}

type UserInvitation struct {
	ID             uuid.UUID
	Email          string
	Name           *string
	Token          string
	TokenExpiresAt pgtype.Timestamp
	EntityID       *uuid.UUID
	InvitationType string
	EntityRole     *string
	InvitedAt      pgtype.Timestamp
	ClaimedAt      pgtype.Timestamp
}

type Vehicle struct {
	ID                 uuid.UUID
	OwnerID            *uuid.UUID
	ChassisNumber      string
	LicensePlate       string
	EngineNumber       string
	TransmissionNumber string
	Make               string
	Model              string
	Year               int32
	Color              string
	BodyType           string
	DriveType          string
	GearType           string
	SuspensionType     string
	Cid                *string
	CidSourceJson      *string
	CidSourceCborB64   *string
	BlockchainAssetID  string
	CreatedAt          pgtype.Timestamp
	UpdatedAt          pgtype.Timestamp
	Fuel               string
	EngineCc           *int32
	EngineCylinders    *int32
	EnginePowerHp      *int32
	BlockchainStatus   string
}

type VehicleDocument struct {
	ID        uuid.UUID
	VehicleID uuid.UUID
	ObjectKey string
	Filename  string
	UploadUrl *string
	CreatedAt pgtype.Timestamp
}

type VehicleInvitation struct {
	ID             uuid.UUID
	VehicleID      uuid.UUID
	Email          string
	InvitedAt      pgtype.Timestamp
	ClaimedAt      pgtype.Timestamp
	Token          *string
	TokenExpiresAt pgtype.Timestamp
}

type VehiclePhoto struct {
	ID        uuid.UUID
	VehicleID uuid.UUID
	ObjectKey string
	UploadUrl *string
	CreatedAt pgtype.Timestamp
}

type VehicleShareLink struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	Token            string
	CanViewDetails   bool
	CanViewPhotos    bool
	CanViewDocuments bool
	CanViewHistory   bool
	RecipientEmail   *string
	ExpiresAt        pgtype.Timestamp
	CreatedAt        pgtype.Timestamp
	AccessedCount    int32
	LastAccessedAt   pgtype.Timestamp
	RevokedAt        pgtype.Timestamp
}
