// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: photos.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const confirmPhotoUpload = `-- name: ConfirmPhotoUpload :one
UPDATE vehicle_photos
SET upload_url = NULL
WHERE id = $1
RETURNING id, vehicle_id, object_key, upload_url, created_at
`

func (q *Queries) ConfirmPhotoUpload(ctx context.Context, id uuid.UUID) (VehiclePhoto, error) {
	row := q.db.QueryRow(ctx, confirmPhotoUpload, id)
	var i VehiclePhoto
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const countPhotosByVehicle = `-- name: CountPhotosByVehicle :one
SELECT COUNT(*) FROM vehicle_photos
WHERE vehicle_id = $1
`

func (q *Queries) CountPhotosByVehicle(ctx context.Context, vehicleID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPhotosByVehicle, vehicleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPhoto = `-- name: CreatePhoto :one
INSERT INTO vehicle_photos (
    vehicle_id, object_key, upload_url
) VALUES (
    $1, $2, $3
)
RETURNING id, vehicle_id, object_key, upload_url, created_at
`

type CreatePhotoParams struct {
	VehicleID uuid.UUID
	ObjectKey string
	UploadUrl *string
}

func (q *Queries) CreatePhoto(ctx context.Context, arg CreatePhotoParams) (VehiclePhoto, error) {
	row := q.db.QueryRow(ctx, createPhoto, arg.VehicleID, arg.ObjectKey, arg.UploadUrl)
	var i VehiclePhoto
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhoto = `-- name: DeletePhoto :exec
DELETE FROM vehicle_photos
WHERE id = $1
`

func (q *Queries) DeletePhoto(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePhoto, id)
	return err
}

const getPhoto = `-- name: GetPhoto :one
SELECT id, vehicle_id, object_key, upload_url, created_at FROM vehicle_photos
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPhoto(ctx context.Context, id uuid.UUID) (VehiclePhoto, error) {
	row := q.db.QueryRow(ctx, getPhoto, id)
	var i VehiclePhoto
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getPhotoByKey = `-- name: GetPhotoByKey :one
SELECT id, vehicle_id, object_key, upload_url, created_at FROM vehicle_photos
WHERE vehicle_id = $1 AND object_key = $2 LIMIT 1
`

type GetPhotoByKeyParams struct {
	VehicleID uuid.UUID
	ObjectKey string
}

func (q *Queries) GetPhotoByKey(ctx context.Context, arg GetPhotoByKeyParams) (VehiclePhoto, error) {
	row := q.db.QueryRow(ctx, getPhotoByKey, arg.VehicleID, arg.ObjectKey)
	var i VehiclePhoto
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.ObjectKey,
		&i.UploadUrl,
		&i.CreatedAt,
	)
	return i, err
}

const listPhotosByVehicle = `-- name: ListPhotosByVehicle :many
SELECT id, vehicle_id, object_key, upload_url, created_at FROM vehicle_photos
WHERE vehicle_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPhotosByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]VehiclePhoto, error) {
	rows, err := q.db.Query(ctx, listPhotosByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehiclePhoto{}
	for rows.Next() {
		var i VehiclePhoto
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.ObjectKey,
			&i.UploadUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
