// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddUserToEntity(ctx context.Context, arg AddUserToEntityParams) (UserEntity, error)
	CheckUserEntityMembership(ctx context.Context, arg CheckUserEntityMembershipParams) (bool, error)
	ClaimInvitation(ctx context.Context, id uuid.UUID) (ClaimInvitationRow, error)
	ClaimInvitationsByEmail(ctx context.Context, email string) error
	ClaimUserInvitation(ctx context.Context, token string) error
	ClaimVehicle(ctx context.Context, arg ClaimVehicleParams) (Vehicle, error)
	ConfirmDocumentUpload(ctx context.Context, id uuid.UUID) (VehicleDocument, error)
	ConfirmPhotoUpload(ctx context.Context, id uuid.UUID) (VehiclePhoto, error)
	CountDocumentsByVehicle(ctx context.Context, vehicleID uuid.UUID) (int64, error)
	CountEntities(ctx context.Context) (int64, error)
	CountEntitiesByType(ctx context.Context, entityType string) (int64, error)
	CountPhotosByVehicle(ctx context.Context, vehicleID uuid.UUID) (int64, error)
	CountVehicles(ctx context.Context) (int64, error)
	CountVehiclesByOwner(ctx context.Context, ownerID *uuid.UUID) (int64, error)
	CreateDocument(ctx context.Context, arg CreateDocumentParams) (VehicleDocument, error)
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error)
	CreatePhoto(ctx context.Context, arg CreatePhotoParams) (VehiclePhoto, error)
	CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (VehicleShareLink, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserInvitation(ctx context.Context, arg CreateUserInvitationParams) (UserInvitation, error)
	CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error)
	DeleteDocument(ctx context.Context, id uuid.UUID) error
	DeleteEntity(ctx context.Context, id uuid.UUID) error
	DeleteEvent(ctx context.Context, id uuid.UUID) error
	DeleteExpiredShareLinks(ctx context.Context) error
	DeleteInvitation(ctx context.Context, id uuid.UUID) error
	DeletePhoto(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	DeleteUserInvitation(ctx context.Context, id uuid.UUID) error
	DeleteVehicle(ctx context.Context, id uuid.UUID) error
	GetAllPendingInvitations(ctx context.Context) ([]GetAllPendingInvitationsRow, error)
	GetDocument(ctx context.Context, id uuid.UUID) (VehicleDocument, error)
	GetDocumentByKey(ctx context.Context, arg GetDocumentByKeyParams) (VehicleDocument, error)
	GetEntity(ctx context.Context, id uuid.UUID) (Entity, error)
	GetEntityMembers(ctx context.Context, entityID uuid.UUID) ([]GetEntityMembersRow, error)
	GetEvent(ctx context.Context, id uuid.UUID) (Event, error)
	GetInvitationByID(ctx context.Context, id uuid.UUID) (GetInvitationByIDRow, error)
	GetInvitationByToken(ctx context.Context, token *string) (GetInvitationByTokenRow, error)
	GetInvitationsByEmailAndVehicle(ctx context.Context, arg GetInvitationsByEmailAndVehicleParams) ([]GetInvitationsByEmailAndVehicleRow, error)
	GetPendingInvitationsByEmail(ctx context.Context, email string) ([]GetPendingInvitationsByEmailRow, error)
	GetPendingUserInvitationsByEmail(ctx context.Context, email string) ([]UserInvitation, error)
	GetPhoto(ctx context.Context, id uuid.UUID) (VehiclePhoto, error)
	GetPhotoByKey(ctx context.Context, arg GetPhotoByKeyParams) (VehiclePhoto, error)
	GetShareLinkByID(ctx context.Context, id uuid.UUID) (VehicleShareLink, error)
	GetShareLinkByToken(ctx context.Context, token string) (VehicleShareLink, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserEntityMemberships(ctx context.Context, userID uuid.UUID) ([]GetUserEntityMembershipsRow, error)
	GetUserEntityRole(ctx context.Context, arg GetUserEntityRoleParams) (string, error)
	GetUserInvitationByID(ctx context.Context, id uuid.UUID) (UserInvitation, error)
	GetUserInvitationByToken(ctx context.Context, token string) (UserInvitation, error)
	GetVehicle(ctx context.Context, id uuid.UUID) (Vehicle, error)
	GetVehicleByChassisNumber(ctx context.Context, chassisNumber string) (Vehicle, error)
	GetVehicleByLicensePlate(ctx context.Context, licensePlate string) (Vehicle, error)
	IncrementShareLinkAccessCount(ctx context.Context, id uuid.UUID) (VehicleShareLink, error)
	ListDocumentsByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]VehicleDocument, error)
	ListEntities(ctx context.Context, arg ListEntitiesParams) ([]Entity, error)
	ListEntitiesByType(ctx context.Context, arg ListEntitiesByTypeParams) ([]Entity, error)
	ListEventsByEntity(ctx context.Context, entityID *uuid.UUID) ([]Event, error)
	ListEventsByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]Event, error)
	ListPhotosByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]VehiclePhoto, error)
	ListShareLinksByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]VehicleShareLink, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	ListVehicles(ctx context.Context, arg ListVehiclesParams) ([]Vehicle, error)
	ListVehiclesByOwner(ctx context.Context, arg ListVehiclesByOwnerParams) ([]Vehicle, error)
	RemoveUserFromEntity(ctx context.Context, arg RemoveUserFromEntityParams) error
	RevokeShareLink(ctx context.Context, id uuid.UUID) (VehicleShareLink, error)
	UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error)
	UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserEntityRole(ctx context.Context, arg UpdateUserEntityRoleParams) (UserEntity, error)
	UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error)
}

var _ Querier = (*Queries)(nil)
