// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addUserToEntity = `-- name: AddUserToEntity :one
INSERT INTO user_entity (
    user_id,
    entity_id,
    role
) VALUES (
    $1,
    $2,
    $3
) RETURNING user_id, entity_id, role, added_at
`

type AddUserToEntityParams struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
	Role     string
}

func (q *Queries) AddUserToEntity(ctx context.Context, arg AddUserToEntityParams) (UserEntity, error) {
	row := q.db.QueryRow(ctx, addUserToEntity, arg.UserID, arg.EntityID, arg.Role)
	var i UserEntity
	err := row.Scan(
		&i.UserID,
		&i.EntityID,
		&i.Role,
		&i.AddedAt,
	)
	return i, err
}

const checkUserEntityMembership = `-- name: CheckUserEntityMembership :one
SELECT EXISTS(
    SELECT 1 FROM user_entity
    WHERE user_id = $1 AND entity_id = $2
) AS is_member
`

type CheckUserEntityMembershipParams struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
}

func (q *Queries) CheckUserEntityMembership(ctx context.Context, arg CheckUserEntityMembershipParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkUserEntityMembership, arg.UserID, arg.EntityID)
	var is_member bool
	err := row.Scan(&is_member)
	return is_member, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    is_admin
) VALUES (
    $1,
    $2
) RETURNING id, is_admin, created_at, updated_at
`

type CreateUserParams struct {
	ID      uuid.UUID
	IsAdmin bool
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getEntityMembers = `-- name: GetEntityMembers :many
SELECT ue.user_id, ue.entity_id, ue.role, ue.added_at, u.is_admin
FROM user_entity ue
JOIN users u ON ue.user_id = u.id
WHERE ue.entity_id = $1
ORDER BY ue.added_at DESC
`

type GetEntityMembersRow struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
	Role     string
	AddedAt  time.Time
	IsAdmin  bool
}

func (q *Queries) GetEntityMembers(ctx context.Context, entityID uuid.UUID) ([]GetEntityMembersRow, error) {
	rows, err := q.db.Query(ctx, getEntityMembers, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEntityMembersRow{}
	for rows.Next() {
		var i GetEntityMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.EntityID,
			&i.Role,
			&i.AddedAt,
			&i.IsAdmin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, is_admin, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserEntityMemberships = `-- name: GetUserEntityMemberships :many
SELECT ue.user_id, ue.entity_id, ue.role, ue.added_at, e.name as entity_name, e.entity_type
FROM user_entity ue
JOIN entities e ON ue.entity_id = e.id
WHERE ue.user_id = $1
ORDER BY ue.added_at DESC
`

type GetUserEntityMembershipsRow struct {
	UserID     uuid.UUID
	EntityID   uuid.UUID
	Role       string
	AddedAt    time.Time
	EntityName string
	EntityType string
}

func (q *Queries) GetUserEntityMemberships(ctx context.Context, userID uuid.UUID) ([]GetUserEntityMembershipsRow, error) {
	rows, err := q.db.Query(ctx, getUserEntityMemberships, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserEntityMembershipsRow{}
	for rows.Next() {
		var i GetUserEntityMembershipsRow
		if err := rows.Scan(
			&i.UserID,
			&i.EntityID,
			&i.Role,
			&i.AddedAt,
			&i.EntityName,
			&i.EntityType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEntityRole = `-- name: GetUserEntityRole :one
SELECT role FROM user_entity
WHERE user_id = $1 AND entity_id = $2
`

type GetUserEntityRoleParams struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
}

func (q *Queries) GetUserEntityRole(ctx context.Context, arg GetUserEntityRoleParams) (string, error) {
	row := q.db.QueryRow(ctx, getUserEntityRole, arg.UserID, arg.EntityID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, is_admin, created_at, updated_at FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.IsAdmin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromEntity = `-- name: RemoveUserFromEntity :exec
DELETE FROM user_entity
WHERE user_id = $1 AND entity_id = $2
`

type RemoveUserFromEntityParams struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
}

func (q *Queries) RemoveUserFromEntity(ctx context.Context, arg RemoveUserFromEntityParams) error {
	_, err := q.db.Exec(ctx, removeUserFromEntity, arg.UserID, arg.EntityID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET is_admin = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, is_admin, created_at, updated_at
`

type UpdateUserParams struct {
	ID      uuid.UUID
	IsAdmin bool
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser, arg.ID, arg.IsAdmin)
	var i User
	err := row.Scan(
		&i.ID,
		&i.IsAdmin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserEntityRole = `-- name: UpdateUserEntityRole :one
UPDATE user_entity
SET role = $3
WHERE user_id = $1 AND entity_id = $2
RETURNING user_id, entity_id, role, added_at
`

type UpdateUserEntityRoleParams struct {
	UserID   uuid.UUID
	EntityID uuid.UUID
	Role     string
}

func (q *Queries) UpdateUserEntityRole(ctx context.Context, arg UpdateUserEntityRoleParams) (UserEntity, error) {
	row := q.db.QueryRow(ctx, updateUserEntityRole, arg.UserID, arg.EntityID, arg.Role)
	var i UserEntity
	err := row.Scan(
		&i.UserID,
		&i.EntityID,
		&i.Role,
		&i.AddedAt,
	)
	return i, err
}
