// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: vehicle_share_links.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShareLink = `-- name: CreateShareLink :one
INSERT INTO vehicle_share_links (
  vehicle_id,
  token,
  can_view_details,
  can_view_photos,
  can_view_documents,
  can_view_history,
  recipient_email,
  expires_at
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, vehicle_id, token, can_view_details, can_view_photos, can_view_documents, can_view_history, recipient_email, expires_at, created_at, accessed_count, last_accessed_at, revoked_at
`

type CreateShareLinkParams struct {
	VehicleID        uuid.UUID
	Token            string
	CanViewDetails   bool
	CanViewPhotos    bool
	CanViewDocuments bool
	CanViewHistory   bool
	RecipientEmail   *string
	ExpiresAt        pgtype.Timestamptz
}

func (q *Queries) CreateShareLink(ctx context.Context, arg CreateShareLinkParams) (VehicleShareLink, error) {
	row := q.db.QueryRow(ctx, createShareLink,
		arg.VehicleID,
		arg.Token,
		arg.CanViewDetails,
		arg.CanViewPhotos,
		arg.CanViewDocuments,
		arg.CanViewHistory,
		arg.RecipientEmail,
		arg.ExpiresAt,
	)
	var i VehicleShareLink
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Token,
		&i.CanViewDetails,
		&i.CanViewPhotos,
		&i.CanViewDocuments,
		&i.CanViewHistory,
		&i.RecipientEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AccessedCount,
		&i.LastAccessedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteExpiredShareLinks = `-- name: DeleteExpiredShareLinks :exec
DELETE FROM vehicle_share_links
WHERE expires_at < CURRENT_TIMESTAMP AND revoked_at IS NULL
`

func (q *Queries) DeleteExpiredShareLinks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredShareLinks)
	return err
}

const getShareLinkByID = `-- name: GetShareLinkByID :one
SELECT id, vehicle_id, token, can_view_details, can_view_photos, can_view_documents, can_view_history, recipient_email, expires_at, created_at, accessed_count, last_accessed_at, revoked_at FROM vehicle_share_links
WHERE id = $1
`

func (q *Queries) GetShareLinkByID(ctx context.Context, id uuid.UUID) (VehicleShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByID, id)
	var i VehicleShareLink
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Token,
		&i.CanViewDetails,
		&i.CanViewPhotos,
		&i.CanViewDocuments,
		&i.CanViewHistory,
		&i.RecipientEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AccessedCount,
		&i.LastAccessedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getShareLinkByToken = `-- name: GetShareLinkByToken :one
SELECT id, vehicle_id, token, can_view_details, can_view_photos, can_view_documents, can_view_history, recipient_email, expires_at, created_at, accessed_count, last_accessed_at, revoked_at FROM vehicle_share_links
WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) GetShareLinkByToken(ctx context.Context, token string) (VehicleShareLink, error) {
	row := q.db.QueryRow(ctx, getShareLinkByToken, token)
	var i VehicleShareLink
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Token,
		&i.CanViewDetails,
		&i.CanViewPhotos,
		&i.CanViewDocuments,
		&i.CanViewHistory,
		&i.RecipientEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AccessedCount,
		&i.LastAccessedAt,
		&i.RevokedAt,
	)
	return i, err
}

const incrementShareLinkAccessCount = `-- name: IncrementShareLinkAccessCount :one
UPDATE vehicle_share_links
SET accessed_count = accessed_count + 1,
    last_accessed_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, vehicle_id, token, can_view_details, can_view_photos, can_view_documents, can_view_history, recipient_email, expires_at, created_at, accessed_count, last_accessed_at, revoked_at
`

func (q *Queries) IncrementShareLinkAccessCount(ctx context.Context, id uuid.UUID) (VehicleShareLink, error) {
	row := q.db.QueryRow(ctx, incrementShareLinkAccessCount, id)
	var i VehicleShareLink
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Token,
		&i.CanViewDetails,
		&i.CanViewPhotos,
		&i.CanViewDocuments,
		&i.CanViewHistory,
		&i.RecipientEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AccessedCount,
		&i.LastAccessedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listShareLinksByVehicle = `-- name: ListShareLinksByVehicle :many
SELECT id, vehicle_id, token, can_view_details, can_view_photos, can_view_documents, can_view_history, recipient_email, expires_at, created_at, accessed_count, last_accessed_at, revoked_at FROM vehicle_share_links
WHERE vehicle_id = $1 AND revoked_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListShareLinksByVehicle(ctx context.Context, vehicleID uuid.UUID) ([]VehicleShareLink, error) {
	rows, err := q.db.Query(ctx, listShareLinksByVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleShareLink{}
	for rows.Next() {
		var i VehicleShareLink
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Token,
			&i.CanViewDetails,
			&i.CanViewPhotos,
			&i.CanViewDocuments,
			&i.CanViewHistory,
			&i.RecipientEmail,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.AccessedCount,
			&i.LastAccessedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeShareLink = `-- name: RevokeShareLink :one
UPDATE vehicle_share_links
SET revoked_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, vehicle_id, token, can_view_details, can_view_photos, can_view_documents, can_view_history, recipient_email, expires_at, created_at, accessed_count, last_accessed_at, revoked_at
`

func (q *Queries) RevokeShareLink(ctx context.Context, id uuid.UUID) (VehicleShareLink, error) {
	row := q.db.QueryRow(ctx, revokeShareLink, id)
	var i VehicleShareLink
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Token,
		&i.CanViewDetails,
		&i.CanViewPhotos,
		&i.CanViewDocuments,
		&i.CanViewHistory,
		&i.RecipientEmail,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.AccessedCount,
		&i.LastAccessedAt,
		&i.RevokedAt,
	)
	return i, err
}
